### ISSUE TITLE
css 外部资源路径处理的问题

### ISSUE THREAD

**Issue by hotoo** [spmjs/gulp-spm#34]
bootstrap 中有 iconfont 使用到 # 号

```css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url(if($bootstrap-sass-asset-helper, twbs-font-path('#{$icon-font-path}#{$icon-font-name}.eot'), '#{$icon-font-path}#{$icon-font-name}.eot'));
  src: url(if($bootstrap-sass-asset-helper, twbs-font-path('#{$icon-font-path}#{$icon-font-name}.eot?#iefix'), '#{$icon-font-path}#{$icon-font-name}.eot?#iefix')) format('embedded-opentype'),
       url(if($bootstrap-sass-asset-helper, twbs-font-path('#{$icon-font-path}#{$icon-font-name}.woff'), '#{$icon-font-path}#{$icon-font-name}.woff')) format('woff'),
       url(if($bootstrap-sass-asset-helper, twbs-font-path('#{$icon-font-path}#{$icon-font-name}.ttf'), '#{$icon-font-path}#{$icon-font-name}.ttf')) format('truetype'),
       url(if($bootstrap-sass-asset-helper, twbs-font-path('#{$icon-font-path}#{$icon-font-name}.svg##{$icon-font-svg-id}'), '#{$icon-font-path}#{$icon-font-name}.svg##{$icon-font-svg-id}')) format('svg');
}
```

build 的时候报错：

```
Error: ENOENT, no such file or directory '.../bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular'
    at Error (native)
    at Object.fs.openSync (fs.js:443:18)
    at Object.fs.readFileSync (fs.js:309:15)
    at /usr/local/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-spm/lib/plugin/css.js:52:26
    at /usr/local/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-spm/node_modules/css-resources/index.js:27:47
    at Array.forEach (native)
    at /usr/local/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-spm/node_modules/css-resources/index.js:26:15
    at Array.forEach (native)
    at /usr/local/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-spm/node_modules/css-resources/index.js:15:23
    at Array.forEach (native)
```

把 gulp-spm/lib/plugin/css.js#L52 文件改成增加 # 标志符号：

```js
          var f = new File({
            cwd: options.pkg.dest,
            base: options.pkg.dest,
            path: depFileName,
            contents: fs.readFileSync(depFilePath.split(/[#?]/)[0])
          });
```

但是又遇到另一种问题：

```css
.lvml {
	behavior: url(#default#VML);
}
```

抛出异常：

```
Error: EISDIR, illegal operation on a directory
    at Error (native)
    at Object.fs.readSync (fs.js:492:19)
    at Object.fs.readFileSync (fs.js:335:28)
    at /usr/local/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-spm/lib/plugin/css.js:52:26
    at /usr/local/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-spm/node_modules/css-resources/index.js:27:47
    at Array.forEach (native)
    at /usr/local/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-spm/node_modules/css-resources/index.js:26:15
    at Array.forEach (native)
    at /usr/local/lib/node_modules/spm/node_modules/spm-build/node_modules/gulp-spm/node_modules/css-resources/index.js:15:23
    at Array.forEach (native)
```
